---
title: "Multivariate Distribution"
format: html
engine: knitr
filters:
  - webr
---

# Basics

Mean vector $\mu' = (\mu_1 , \mu_2, \dots , \mu_k)'; [k>2]$

**Condition of PDF:**

1.  $\int_x f(x) dx = 1$

2.  $f(x) \ge 0$

**Condition of PMF:**

1.  $\sum_x p(x)=1$

2.  $0\le p(x) \le 1$

**Example:**

$f(x) = kx^2; [0\le x \le 1]$ is a pdf. Then find k

**Answer:** Thus f(x) is a pdf,

$\therefore \int_x f(x) dx = 1$

$\Rightarrow \int_0^1 kx^2 dx = 1$

$\Rightarrow \frac{k}{3} [x^3]_0^1=1$

$\Rightarrow \frac{k}{3} \times 1 = 1$

$\therefore k = 3$

Therfore, the pdf is $f(x) = 3x^2; [0\le x \le 1]$

```{r echo=FALSE}
x = seq(0, 1, 0.01)
y = 3*x^2
plot(x, y, type = "l", main=expression(f(x): 3*x^2))
```

## Joint PDF

**X and Y are random variable and the joint pdf is,** $f(x, y) = cx^3y \\ 0 \le x \le 1, y \ge 0$

1.  **Find** $r_{xy}$
2.  

# Multivariate Normal Distribution (MND)

## Introduction

A vector valued random variable $X = (x_1, x_2, \dots, x_p)'$ is said to have a multivarite normal distribution with mean vector $\mu = (\mu_1, \mu_2, \dots , \mu_p)'$ and variance-covariance matrix $\Sigma = \{\sigma_{ij}\}, i, j = 1, 2, \dots, p$ if its pdf is defined as, $$f(X)=\frac{1}{(2\Pi)^{\frac{p}{2}} |\Sigma |^\frac{1}{2}} exp\Big[ -\frac{1}{2} (X-\mu)'\Sigma^{-1} (X-\mu) \Big] $$ or, $$f(X)=(2\Pi)^{-\frac{p}{2}} |\Sigma |^{-\frac{1}{2}} exp\Big[ -\frac{1}{2} (X-\mu)'\Sigma^{-1} (X-\mu) \Big] ----(1)$$ $$-\infty<x_i<\infty, -\infty<\mu_i < \infty \\ \sigma_{ij} > 0; i=1, 2, \dots, p$$

## Derivation of MND

For univariate, $$f(x) = \frac{1}{\sqrt{2\pi \sigma^2}} exp\Big[-\frac12 \frac{(x-\mu)^2}{\sigma^2}\Big]$$ $$\Rightarrow f(x) = k \times  exp\Big[-\frac12 \frac{(x-\mu)(x-\mu)}{\sigma^2}\Big]$$ $$\Rightarrow f(x) = k \times exp\Big[-\frac12 (x-\mu)' (\sigma^2)^{-1}(x-\mu)\Big]$$

Now, for p component multivarite case, we have, $X=(x_1, x_2, \dots, x_p)'= \begin{bmatrix} x_1 \\ x_2 \\ \dots \\ x_p \end{bmatrix}, \mu=\begin{bmatrix} \mu_1 \\ \mu_2 \\ \dots \\ \mu_p \end{bmatrix}$

and $\sigma^2$ is replaced by $\Sigma = \begin{bmatrix} \sigma_{11} & \sigma_{12} & \dots & \sigma_{1p} \\ \sigma_{21} & \sigma_{22} & \dots & \sigma_{2p} \\ \dots & \dots & \dots & \dots \\ \sigma_{p1} & \sigma_{p_2} & \dots & \sigma_{pp} \end{bmatrix}$

$$\therefore f(X) = k \times exp\Big[ -\frac12(X-\mu)' \Sigma^{-1} (X-\mu)\Big] ---(2)$$ $$\infty < x_i , \mu_i<\infty; \sigma_{ij} > 0$$

Here, k i sconstant that can be determined by the integration over the range of the components variable.

$f(X)$ is non-negative because $\Sigma^{-1}$ is a positive definite and $(X-\mu)'\Sigma^{-1}(X-\mu) \ge 0$

$$\therefore \int_{-\infty}^{\infty} \dots \int_{-\infty}^{\infty} f(X) dx_1 \dots dx_p = 1 ----(3)$$ $$\Rightarrow \int_{-\infty}^{\infty} \dots \int_{-\infty}^{\infty} k \times exp\Big[ -\frac12(X-\mu)' \Sigma^{-1} (X-\mu)\Big]  dx_1 \dots dx_p = 1$$ $$\Rightarrow \int_{-\infty}^{\infty} \dots \int_{-\infty}^{\infty} exp\Big[ -\frac12(X-\mu)' \Sigma^{-1} (X-\mu)\Big]  dx_1 \dots dx_p = \frac 1k = k^* \text{ (say)} $$ $----(4)$

We use the fact that if $\Sigma^{-1}$ is a positive definite, then there exists a non-singular matrix C such that, $C'\Sigma^{-1}C=I ----(5)$

Now, let $X-\mu = CY$, where $Y=\begin{bmatrix} y_1 \\ y_2 \\ \dots \\ y_p \end{bmatrix}$,$Y'Y = \begin{bmatrix} y_1 & y_2 & \dots & y_p \end{bmatrix} \begin{bmatrix} y_1 \\ y_2 \\ \dots \\ y_p \end{bmatrix} = \sum y_i^2$

$\therefore dX = |C|dY$

Then, $(X-\mu)' \Sigma^{-1} (X-\mu) = Y'C'\Sigma^{-1}CY = Y'IY=Y'Y = \sum_{i=1}^p y_i^2$

And the Jacobian transformation $J = mod|C|$

# Quadratic Form

$Q=2x_1^2 + x_2^2 + 3x_3^2 + 6x_1x_2 + 9x_2x_3 + 12 x_1x_3$

$\Rightarrow Q = \begin{bmatrix} x_1 & x_2 & x_3  \end{bmatrix} \begin{bmatrix} 2&3&6 \\ 3&1&\frac{9}{2} \\ 6&\frac{9}{2}&3 \end{bmatrix} \begin{bmatrix} x_1 \\ x_2 \\ x_3 \end{bmatrix} = X'AX$

Where, $X =\begin{bmatrix} x_1 \\ x_2 \\ x_3 \end{bmatrix}$ and $A = \begin{bmatrix} 2&3&6 \\ 3&1&\frac{9}{2} \\ 6&\frac{9}{2}&3 \end{bmatrix}$

## Properties of Quadratic Form

1. A quadratic form $Q=X'AX$ is a homogeneous polynomial of degree two with any number of variables. 

2. If $X \sim N_p (\mu, \Sigma)$, then the quardatic form $Q_1 = X'AX$ and $Q_2 =X'BX$ are independent iff $A\Sigma B=0$.

3. If $X \sim N_p (0, I)$, then the quardatic form $Q = X'AX$ follows $\chi^2$-distribution with k-df.

4. If $X \sim N_p (\mu, I)$, then the quardatic form $Q = X'AX \sim \chi'^2$ (Non central $\chi^2$-distribution) with k-df and non-centrility parameter, $\lambda=\frac12 \mu'A\mu$.

5. If $X \sim N_p (0, \Sigma)$, then the quardatic form $Q = X'AX$ follows $\chi^2$-distribution with k-df.

6. If $X \sim N_p (\mu, \Sigma)$, then the m.g.f of quadratic form $Q = X'AX$ is $M_Q (t) = (1-2d_{ii}t)^{-\frac k2}$.


## Use/Application

1. It is used in multivariate normal distribution and analysis.

2. Sometimes is used in ANOVA and congruent reduction.

3. It is used in both central and non-central sampling distribution.

4. To find maximum and minimum values function of the severil variables. 

5. It is used in Wishart and Hotelings' $T^2$-distribution.

6. It is used in derivation of $\chi'^2$ (Non central $\chi^2$).

7. ... And many more