---
title: "Stochastic Processes and Acturial Models"
format: html
engine: knitr
filters:
  - webr
---

# Basics

**Variable:** Values varies form Individual to individual.

**Experiment:** Repeation fo an event is called experiment.

**Random Variable:** Random variable is a variable that associate to probability. Random variable is an stochastic variable.

**Stichastic Processes:** **Stochastic process** or **random process** is a collection of random variables **orderd** by an index set. Let $X_0, X_1, X_2, \dots;$ be a set of random variables; that form a stochastic process ordered by the discrete index set $\{1, 2, 3, \dots\}$.

Notation: For discrete index set, $\{X_n:n=0,1,2,\dots\}$ and $\{Y_t:t\geq0\}$ with continuous index set $\{t:t\geq0\}$.

**Bivariate: Discrete and Continuous** (i) Discrete time, Discrete state space (DD) (ii) Discrete time, Continuous state space (DC) (iii) Continuous time, Discrete state space (CD) (iv) Continuous time, Continuous state space (CC)

# Probability Generating Function (p.g.f)

**For two coin:** TT, TH, HT, HH

|                    |            |            |            |       |
|--------------------|:----------:|:----------:|:----------:|:-----:|
| No of Success $X$  |     0      |     1      |     2      | Total |
| Probability $p(x)$ | $\frac 14$ | $\frac 12$ | $\frac 14$ |  $1$  |
|                    |   $p_0$    |   $p_1$    |   $p_2$    |       |

## Probability Generating Function (pgf)

$p_0$ = { No head }

$p_1$ = { One head }

$p_2 = Pr\{x=2\}$ = { Both are Head }

## Binomial Distribution

$p(x) = {n\choose x} p^x (1-p)^{n-x}; x = 0, 1, 2, \dots , n$

$p(s) = \sum_{k=0}^n p_{k} s^k$\$

$=p_0 s^0 + p_1 s^1 +p_2 s^2 + \dots + p_n s^n$

$={n \choose 0} p^0q^{n-0}s^0 + {n \choose 1} p^1q^{n-1}s^1 +{n \choose 2} p^2q^{n-2}s^2+ \dots + {n \choose n} p^nq^{0}s^n$

$\therefore p(s)=(q+ps)^n$

# Markov Chain

## 2 states and m-steps Markov Chain

$P = \begin{pmatrix} q & p \\ p & q \end{pmatrix}$

$P^2 = \begin{pmatrix} q^2+p^2 & 2pq \\ 2pq & q^2+p^2 \end{pmatrix}$

Now, $q^2+p^2 = \frac{2q^2+2p^2}{2} = \frac{q^2+2pq+p^2 +q^2-2pq+p^2}{2}$

$=\frac{(p+q)^2 + (q-p)^2}{2} = \frac{1+(q-p)^2}{2} = \frac{1}{2}+\frac{(q-p)^2}{2}$

And, $2pq=\frac{4pq}2=\frac{p^2+2pq+q^2-(q^2 - 2pq+p^2)}{2}$

$=\frac{(p+q)^2 - (q-p)^2}{2} = \frac{1-(q-p)^2}{2} = \frac{1}{2}-\frac{(q-p)^2}{2}$

$\therefore P^{(2)} = \begin{pmatrix} \frac 12+\frac{(q-p)^2}2 & \frac 12-\frac{(q-p)^2}2 \\ \frac 12-\frac{(q-p)^2}2 & \frac 12+\frac{(q-p)^2}2\end{pmatrix}$

Similarly, $P^{(3)} = \begin{pmatrix} \frac 12+\frac{(q-p)^3}2 & \frac 12-\frac{(q-p)^3}2 \\ \frac 12-\frac{(q-p)^3}2 & \frac 12+\frac{(q-p)^3}2\end{pmatrix}$

$\therefore P^{(m)} = \begin{pmatrix} \frac 12+\frac{(q-p)^m}2 & \frac 12-\frac{(q-p)^m}2 \\ \frac 12-\frac{(q-p)^m}2 & \frac 12+\frac{(q-p)^m}2\end{pmatrix}$

Here, $\frac{(q-p)^m}2$ is the stochastic part and $\frac12$ is the deterministic part

When, $m \to \infty$, then $\frac{(q-p)^m}2 \to 0$. So the matrix tends to deterministic from stochastic and the P becomes,

$P^{(m)}=\begin{pmatrix} \frac12 & \frac12 \\ \frac12 & \frac 12\end{pmatrix}$
